// templates/svelte/vite-wagmi/src/components/NetworkSwitcher.svelte
<script lang="ts">
  import { switchChain } from "@wagmi/core";
  import { wagmiConfig, wagmiStore } from "../wagmi";
  import { get } from "svelte/store";
  import { useAsync } from "../composables/useAsync";
  import type { Chain } from "viem";

  $: ({ account } = get(wagmiStore));

  const chains: readonly Chain[] = wagmiConfig.chains;

  const { execute: switchNetwork, state: asyncState } = useAsync(switchChain);
  $: ({ inProgress, error } = $asyncState);

  const handleSwitchNetwork = async (chainId: number) => {
    if (account.isConnected) {
      try {
        await switchNetwork(wagmiConfig, { chainId });
      } catch (err) {
        console.error("Error switching network:", err);
      }
    }
  };

  $: currentChain = chains.find((chain) => chain.id === account.chainId) || null;
</script>

<div>
  <div>
    Connected to {currentChain?.name ?? currentChain?.id}
  </div>
  <br />
  <div>
    Switch to:
    {#each chains as item (item.id)}
      <button
        on:click={() => handleSwitchNetwork(item.id)}
        disabled={!account.isConnected || currentChain?.id === item.id}
      >
        {item.name}
      </button>
    {/each}
  </div>
  {#if error}
    <div>Error: {error?.message}</div>
  {/if}
</div>

// templates/vue/vite-wagmi/src/components/NetworkSwitcher.vue
<template>
  <div>
    <div>
      Connected to {{ currentChain?.name ?? currentChain?.id }}
    </div>
    <br />
    <div>
      Switch to:
      <button
        v-for="chain in chains"
        :key="chain.id"
        @click="handleSwitchNetwork(chain.id)"
        :disabled="!account.isConnected || currentChain?.id === chain.id"
      >
        {{ chain.name }}
      </button>
    </div>

    <div v-if="error">Error: {{ error?.message }}</div>
  </div>
</template>

<script lang="ts" setup>
import { ref, onMounted, computed } from 'vue';
import { switchChain, getAccount } from '@wagmi/core';
import { useAsync } from '@/composables/useAsync';
import { wagmiConfig } from '../wagmi';
import { Chain } from 'viem';

const account = ref(getAccount(wagmiConfig));
const { execute: switchNetwork, error } = useAsync(switchChain);

const chains = ref<Chain[]>([...wagmiConfig.chains]);

const currentChain = computed(() => {
  return chains.value.find((chain) => chain.id === account.value.chainId) || null;
});

const handleSwitchNetwork = async (chainId: number) => {
  if (account.value.isConnected) {
    await switchNetwork(wagmiConfig, { chainId });
  }
};

</script>onMounted(() => {
  account.value = getAccount(wagmiConfig);
});
