// templates/svelte/sveltekit-wagmi/src/components/ReadTokenBalance.svelte
<script lang="ts">
  import { readContract } from "@wagmi/core";
  import { useAsync } from "../composables/useAsync";
  import { wagmiStore } from "../stores/wagmi";
  import { daiContractConfig } from "../utils/contracts";
  import { onMount } from "svelte";

  $: ({ account } = $wagmiStore);

  const {
    state: asyncState,
    execute: fetchBalance,
  } = useAsync(async () => {
    return await readContract({
      ...daiContractConfig,
      functionName: "balanceOf",
      args: [account.address!],
    });
  });
  $: ({ inProgress, error, result: balance } = $asyncState);

  onMount(fetchBalance);
</script>

<div>
  <div>
    Token balance: {balance?.toString() ?? ""}
  </div>
  <div>
    <input
      bind:value={account.address}
      type="text"
      placeholder="wallet address"
    />
    <button on:click={fetchBalance}
      >{inProgress ? "fetching..." : "refetch"}</button
    >
  </div>
  {#if error}
    <div>Error: {error?.message}</div>
  {/if}
</div>

// templates/vue/vite-wagmi/src/components/ReadTokenBalance.vue
<template>
  <div>
    <div>
      Token balance: {{ balance?.toString() }}
    </div>
    <div>
      <input v-model="address" type="text" placeholder="wallet address">
      <button @click="fetchBalance">{{ inProgress ? 'fetching...' : 'refetch' }}</button>
    </div>
    <div v-if="error">Error: {{ error?.message }}</div>
  </div>
</template>

<script lang="ts" setup>
import { ref } from "vue"
import { readContract } from '@wagmi/core';

import { daiContractConfig } from '@/utils/contracts';
import { useAsync } from '@/composables/useAsync';
import { account } from '@/wagmi';

const address = ref(account.value.address);

const { result: balance, execute: fetchBalance, inProgress, error} = useAsync(async () => {
  return await readContract({
    ...daiContractConfig,
    functionName: 'balanceOf',
    args: [address.value!],
  })
});

fetchBalance();
</script>
