// templates/svelte/svelte-wagmi-web3modal/src/components/FindBalance.svelte
<script lang="ts" setup>
  import { useAsync } from "../composables/useAsync";
  import { fetchBalance as wagmiFetchBalance, type Address } from "@wagmi/core";

  const { state: asyncState, execute: fetchBalance } =
    useAsync(wagmiFetchBalance);
  $: ({ result: balance, error, inProgress } = $asyncState);

  let address: Address = "0x";
</script>

<div>
  <div>
    Find balance:
    <input bind:value={address} type="text" placeholder="wallet address" />
    <button on:click={() => fetchBalance({ address })}
      >{inProgress ? "fetching..." : "fetch"}</button
    >
  </div>
  <div>{balance?.formatted || ""}</div>
  {#if error}
    <div>Error: {error?.message}</div>
  {/if}
</div>

// templates/vue/nuxt3-wagmi-web3modal/components/FindBalance.vue
<template>
  <div>
    <div>
      Find balance:
      <input v-model="address" type="text" placeholder="wallet address">
      <button @click="() => fetchBalance({ address: address as Address })">{{ inProgress ? 'fetching...' : 'fetch' }}</button>
    </div>
    <div>{{ balance?.formatted }}</div>
    <div v-if="error">Error: {{ error?.message }}</div>
  </div>
</template>

<script lang="ts" setup>
import { fetchBalance as wagmiFetchBalance, type Address } from '@wagmi/core';

const address = ref("");

const { result: balance, execute: fetchBalance, inProgress, error} = useAsync(wagmiFetchBalance);
</script>
