// templates/svelte/vite-wagmi-web3modal/src/components/Token.svelte
<script lang="ts">
  import { writable } from 'svelte/store';
  import { readContracts } from '@wagmi/core';
  import { erc20Abi } from "viem";
  import { get } from 'svelte/store';
  import { wagmiConfig } from '../wagmi';
  import { daiContractConfig } from '../utils/contracts';

  type TokenResult = [number, string, string, bigint];

  let tokenAddress = writable(daiContractConfig.address);
  let token = writable<TokenResult | null>(null); 
  let inProgress = writable(false);
  let error = writable<Error | null>(null);

  const fetchToken = async () => {
    inProgress.set(true);
    error.set(null);

    try {
      const result = await readContracts(wagmiConfig, {
        allowFailure: false, 
        contracts: [
          {
            address: get(tokenAddress), 
            abi: erc20Abi,
            functionName: 'decimals',
          },
          {
            address: get(tokenAddress), 
            abi: erc20Abi,
            functionName: 'name',
          },
          {
            address: get(tokenAddress), 
            abi: erc20Abi,
            functionName: 'symbol',
          },
          {
            address: get(tokenAddress), 
            abi: erc20Abi,
            functionName: 'totalSupply',
          },
        ],
      });

      token.set(result);
    } catch (err) {
      error.set(err as Error);
    } finally {
      inProgress.set(false);
    }
  };

  const fetchCurrentToken = () => {
    fetchToken();
  };
</script>

<form on:submit|preventDefault={fetchCurrentToken}>
  <input bind:value={$tokenAddress} placeholder="token address" />
  <button type="submit">fetch</button>
</form>

<div>
  {#if $inProgress}
    Fetching token...
  {:else if $token}
    <pre>{JSON.stringify($token, (key, value) => typeof value === 'bigint' ? value.toString() : value, 4)}</pre>
  {:else if $error}
    Error: {$error.message}
  {/if}
</div>

// templates/vue/nuxt3-wagmi-web3modal/components/Token.vue
<template>
  <div>
    <form @submit.prevent="fetchCurrentToken">
      <input v-model="tokenAddress" placeholder="token address" />
      <button type="submit">fetch</button>
    </form>
    <div v-if="inProgress">Fetching token...</div>
    <div v-else-if="token">
      <pre>{{ stringify(token, null, 4) }}</pre>
    </div>
    <div v-else-if="error">Error: {{ error?.message }}</div>
  </div>
</template>

<script lang="ts" setup>
import { ref } from "vue";
import { readContracts } from '@wagmi/core';
import { stringify } from '@/utils/formatters';
import { daiContractConfig } from '@/utils/contracts';
import { useAsync } from '@/composables/useAsync';
import { erc20Abi } from "viem";
import { wagmiConfig } from '../store/wagmi.js';

const tokenAddress = ref(daiContractConfig.address);

const { result: token, execute: fetchToken, inProgress, error } = useAsync(async () => {
  return await readContracts(wagmiConfig, {
    allowFailure: false, 
    contracts: [
      {
        address: tokenAddress.value, 
        abi: erc20Abi,
        functionName: 'decimals',
      },
      {
        address: tokenAddress.value, 
        abi: erc20Abi,
        functionName: 'name',
      },
      {
        address: tokenAddress.value, 
        abi: erc20Abi,
        functionName: 'symbol',
      },
      {
        address: tokenAddress.value, 
        abi: erc20Abi,
        functionName: 'totalSupply',
      },
    ],
  });
});

const fetchCurrentToken = () => {
  fetchToken();
};
</script>
