// templates/svelte/sveltekit-wagmi-web3modal/src/components/WatchPendingTransactions.svelte
<script lang="ts">
  import { onDestroy } from 'svelte';
  import { writable, derived } from 'svelte/store';
  import { watchPendingTransactions } from '@wagmi/core';
  import type { Hash } from 'viem';
  import { wagmiConfig } from '../stores/wagmi';

  let transactionHashes = writable<Hash[]>([]);

  let reversedTransactionHashes = derived(transactionHashes, $transactionHashes =>
    [...$transactionHashes].reverse()
  );

  const unwatch = watchPendingTransactions(wagmiConfig, {
    onTransactions(newHashes) {
      transactionHashes.update(existingHashes => 
        Array.from(new Set([...existingHashes, ...newHashes]))
      );
    },
  });

  onDestroy(() => {
    unwatch();
  });
</script>

<div>
  <details>
    <summary>{$reversedTransactionHashes.length} transaction hashes</summary>
    <pre>{$reversedTransactionHashes.join('\n')}</pre>
  </details>
</div>

// templates/vue/nuxt3-wagmi-web3modal/components/WatchPendingTransactions.vue
<template>
  <div>
    <details>
      <summary>{{ reversedTransactionHashes.length }} transaction hashes</summary>
      {{ reversedTransactionHashes.join('\n') }}
    </details>
  </div>
</template>

<script lang="ts" setup>
import { watchPendingTransactions } from '@wagmi/core';
import type { Hash } from 'viem';
import { wagmiConfig } from '../store/wagmi.js';

const transactionHashes = ref<Hash[]>([]);

const reversedTransactionHashes = computed(() => [...transactionHashes.value].reverse());

watchEffect(() => {
  const unwatch = watchPendingTransactions(wagmiConfig, {
    onTransactions(newHashes) {
      transactionHashes.value = Array.from(new Set([...transactionHashes.value, ...newHashes]));
    },
  });

  // Clean up the watcher when the component is unmounted
  return () => {
    unwatch();
  };
});
</script>
