// templates/svelte/vite-wagmi/src/components/WatchContractEvents.svelte
<script lang="ts">
  import { onDestroy } from 'svelte';
  import { writable } from 'svelte/store';
  import { watchContractEvent } from '@wagmi/core';
  import type { Log } from 'viem';
  import { daiContractConfig } from '../utils/contracts';
  import { wagmiConfig } from '../wagmi';

  let events = writable<Log[]>([]);

  const unsubscribe = watchContractEvent(wagmiConfig, {
    ...daiContractConfig,
    eventName: 'Transfer',
    onLogs(logs) {
      events.update(existingLogs => [...existingLogs, ...logs]);
    },
  });

  onDestroy(() => {
    unsubscribe();
  });
</script>

<div>
  <details>
    <summary>{$events.length} DAI `Transfer`s logged</summary>
    <pre>
    {$events
      .slice() 
      .reverse()
      .map((log) => JSON.stringify(log, null, 2)) 
      .join('\n\n\n\n')}
    </pre>
  </details>
</div>

// templates/vue/nuxt3-wagmi-web3modal/components/WatchContractEvents.vue
<template>
  <div>
    <details>
      <summary>{{ events.length }} DAI `Transfer`s logged</summary>
      
      {{
        events
          .reverse()
          .map((log) => stringify(log))
          .join('\n\n\n\n')
      }}
    </details>
  </div>
</template>

<script lang="ts" setup>
import type { Log } from 'viem';
import { watchContractEvent } from '@wagmi/core';
import { stringify } from '@/utils/formatters';
import { wagmiConfig } from '../store/wagmi.js';

const events = ref<Log[]>([]);

watchContractEvent(wagmiConfig, {
  ...daiContractConfig,
  eventName: 'Transfer',
    onLogs(logs) {
      events.value.push(...logs);
    },
});
</script>
