// templates/svelte/sveltekit-wagmi-web3modal/src/components/WatchContractEvents.svelte
<script lang="ts">
  import type { Log } from "viem";
  import { watchContractEvent } from "@wagmi/core";
  import { daiContractConfig } from "../utils/contracts";
  import { stringify } from "../utils/formatters";

  let events: Log[] = [];

  watchContractEvent(
    {
      ...daiContractConfig,
      eventName: "Transfer",
    },
    (logs) => {
      events = [...events, ...logs];
    }
  );
</script>

<div>
  <details>
    <summary>{events.length} DAI `Transfer`s logged</summary>

    {events
      .reverse()
      .map((log) => stringify(log))
      .join("\n\n\n\n")}
  </details>
</div>

// templates/vue/nuxt3-wagmi-web3modal/components/WatchContractEvents.vue
<template>
  <div>
    <details>
      <summary>{{ events.length }} DAI `Transfer`s logged</summary>
      
      {{
        events
          .reverse()
          .map((log) => stringify(log))
          .join('\n\n\n\n')
      }}
    </details>
  </div>
</template>

<script lang="ts" setup>
import type { Log } from 'viem';
import { watchContractEvent } from '@wagmi/core';

const events = ref<Log[]>([]);

watchContractEvent({
  ...daiContractConfig,
  eventName: 'Transfer'
}, (logs) => {
  events.value.push(...logs);
});
</script>
