// templates/vue/nuxt3-ethers/components/Balance.vue
<template>
  <div>
    <div>
      Connected wallet balance:
      {{ balance ? ethers.formatEther(balance): "" }}
      <button @click="getAccountBalance">refetch</button>
    </div>
    <div v-if="error">Error: {{ error?.message }}</div>
  </div>
</template>

<script lang="ts" setup>
import { ethers } from 'ethers';

const { getProvider } = useEthers()
const { account } = storeToRefs(useEthers())

const { result: balance, execute: fetchBalance, inProgress, error} = useAsync((address) => getProvider()!.getBalance(address));
const getAccountBalance = () => fetchBalance(account.value.address);

watch(account, ({ address }) => {
  if (!address) return;
  getAccountBalance();
}, { immediate: true });
</script>

// templates/svelte/vite-ethers/src/components/Balance.svelte
<script lang="ts">
  import { ethers } from "ethers";
  import { etherStore } from "../ethers";
  import { useAsync } from "../composables/useAsync";

  const { state: asyncState, execute: fetchBalance } = useAsync((address) =>
    etherStore.getProvider()!.getBalance(address),
  );
  $: ({ result: balance, error, inProgress } = $asyncState);

  const getAccountBalance = () => fetchBalance($etherStore.account.address);
  $: $etherStore.account.address && getAccountBalance();
</script>

<div>
  <div>
    Connected wallet balance:
    {balance ? ethers.formatEther(balance) : ""}
    <button on:click={getAccountBalance}>refetch</button>
  </div>
  {#if error}
    Error: {error?.message}
  {/if}
</div>
