// templates/vue/nuxt3-ethers/components/FindBalance.vue
<template>
  <div>
    <div>
      Find balance:
      <input v-model="address" type="text" placeholder="wallet address">
      <button @click="() => fetchBalance(address)">{{ inProgress ? 'fetching...' : 'fetch' }}</button>
    </div>
    <div>{{ balance ? ethers.formatEther(balance): "" }}</div>
    <div v-if="error">Error: {{ error?.message }}</div>
  </div>
</template>

<script lang="ts" setup>
import { ethers } from 'ethers';

const { getProvider } = useEthers()

const address = ref("");

const { result: balance, execute: fetchBalance, inProgress, error} = useAsync((address) => getProvider()!.getBalance(address));
</script>

// templates/svelte/vite-ethers/src/components/FindBalance.svelte
<script lang="ts" setup>
  import { ethers } from "ethers";
  import { useAsync } from "../composables/useAsync";
  import { etherStore } from "../ethers";

  const { state: asyncState, execute: fetchBalance } = useAsync((address) =>
    etherStore.getProvider()!.getBalance(address),
  );
  $: ({ result: balance, error, inProgress } = $asyncState);

  let address = "";
</script>

<div>
  <div>
    Find balance:
    <input bind:value={address} type="text" placeholder="wallet address" />
    <button on:click={() => fetchBalance(address)}
      >{inProgress ? "fetching..." : "fetch"}</button
    >
  </div>
  <div>{balance ? ethers.formatEther(balance) : ""}</div>
  {#if error}
    <div>Error: {error?.message}</div>
  {/if}
</div>
