// templates/svelte/sveltekit-ethers/src/components/Connect.svelte
<script lang="ts">
  import { etherStore } from "../stores/ethers";

  const { connect, disconnect } = etherStore;
  $: ({ account } = $etherStore);
</script>

<div>
  {#if account.isConnected}
    <button on:click={disconnect}> Disconnect wallet </button>
  {:else}
    <button on:click={connect}> Connect wallet </button>
  {/if}
</div>

// templates/vue/vite-ethers/src/components/Connect.vue
<template>
  <div>
    <button v-if="account.isConnected" @click="disconnect">
      Disconnect wallet
    </button>

    <button v-else @click="connect()">
      Connect wallet
    </button>
  </div>
</template>

<script lang="ts" setup>
import { connect, disconnect, account } from "@/ethers"
</script>
