// templates/vue/vite-ethers5/src/components/NetworkSwitcher.vue
<template>
  <div>
    <div>
      Connected to {{ network?.name ?? network?.id }}
      <span v-if="network?.unsupported">(unsupported)</span>
    </div>
    <br />
    <div>
      Switch to:
      <button v-for="(item, index) in chains" :key="index" @click="switchNetwork(item.id)">
        {{ item.name }}
      </button>
    </div>

    <div v-if="error">Error: {{ error?.message }}</div>
  </div>
</template>

<script lang="ts" setup>
import { useAsync } from '@/composables/useAsync';
import { chains, network, switchNetwork as switchToChainByID } from "@/ethers";

const { execute: switchNetwork, inProgress, error} = useAsync(switchToChainByID);
</script>

// templates/react/vite-ethers/src/components/NetworkSwitcher.tsx
import { useAsync } from '../hooks/useAsync';
import { chains, useEthereum } from './Context';

export function NetworkSwitcher() {
  const { switchNetwork: switchToChainByID, network } = useEthereum();
  const { execute: switchNetwork, inProgress, error } = useAsync(switchToChainByID);

  return (
    <div>
      <div>
        Connected to {network?.name || network?.id}
        {network?.unsupported && <span>(unsupported)</span>}
      </div>
      <br />
      <div>
        Switch to:
        {chains.map((item, index) => (
          <button key={index} onClick={() => switchNetwork(item.id)}>
            {item.name}
          </button>
        ))}
      </div>

      {error && <div>Error: {error.message}</div>}
    </div>
  )
}
