// templates/vue/vite-wagmi-web3modal/src/components/WatchContractEvents.vue
<template>
  <div>
    <details>
      <summary>{{ events.length }} USDC `Transfer`s logged</summary>
      
      {{
        events
          .reverse()
          .map((log) => stringify(log))
          .join('\n\n\n\n')
      }}
    </details>
  </div>
</template>

<script lang="ts" setup>
import { ref } from "vue"
import type { Log } from 'viem';
import { watchContractEvent } from '@wagmi/core';

import { stringify } from '@/utils/formatters';
import { usdcContractConfig } from '@/utils/contracts';

const events = ref<Log[]>([]);

watchContractEvent({
  ...usdcContractConfig,
  eventName: 'Transfer'
}, (logs) => {
  events.value.push(...logs);
});
</script>

// templates/react/next-wagmi-rainbowkit/src/components/WatchContractEvents.tsx
'use client'

import { useState } from 'react'
import type { Log } from 'viem'
import { useContractEvent } from 'wagmi'

import { usdcContractConfig } from './contracts'
import { stringify } from '../utils/stringify'

export function WatchContractEvents() {
  const [usdcLogs, setUsdcLogs] = useState<Log[]>([])
  useContractEvent({
    ...usdcContractConfig,
    eventName: 'Transfer',
    listener: (logs) => setUsdcLogs((x) => [...x, ...logs]),
  })

  return (
    <div>
      <details>
        <summary>{usdcLogs.length} USDC `Transfer`s logged</summary>
        {usdcLogs
          .reverse()
          .map((log) => stringify(log))
          .join('\n\n\n\n')}
      </details>
    </div>
  )
}
