// templates/vue/vite-wagmi/src/components/Connect.vue
<template>
  <div>
    <button v-if="account.isConnected" @click="disconnect">
      Disconnect from {{ account.connector?.name }}
    </button>

    <template v-else>
      <button v-for="item in config.connectors" :key="item.id" @click="connect({ connector: item })">
        {{ item.name }}
      </button>
    </template>
  </div>
</template>

<script lang="ts" setup>
import { connect, disconnect, getConfig } from '@wagmi/core';
import { account } from "@/wagmi"

const config = getConfig();
</script>

// templates/react/vite-wagmi/src/components/Connect.tsx
import { useAccount, useConnect, useDisconnect } from 'wagmi'

export function Connect() {
  const { connector, isConnected } = useAccount()
  const { connect, connectors, error } = useConnect()
  const { disconnect } = useDisconnect()

  return (
    <div>
      {isConnected && (
        <button onClick={() => disconnect()}>
          Disconnect from {connector?.name}
        </button>
      )}

      {connectors
        .filter((x) => x.id !== connector?.id)
        .map((x) => (
          <button key={x.id} onClick={() => connect({ connector: x })}>
            {x.name}
          </button>
        ))}

      {error && <div>{error.message}</div>}
    </div>
  )
}
