// templates/vue/vite-wagmi/src/components/ReadTokenSupply.vue
<template>
  <div>
    <div>
      Total Supply: {{ supply?.toString() }}
      <button @click="fetchTotalSupply">{{ inProgress ? 'fetching...' : 'refetch' }}</button>
    </div>
    <div v-if="error">Error: {{ error?.message }}</div>
  </div>
</template>

<script lang="ts" setup>
import { readContract } from '@wagmi/core';

import { daiContractConfig } from '@/utils/contracts';
import { useAsync } from '@/composables/useAsync';

const { result: supply, execute: fetchTotalSupply, inProgress, error} = useAsync(async () => {
  return await readContract({
    ...daiContractConfig,
    functionName: 'totalSupply',
  })
});

fetchTotalSupply();
</script>

// templates/svelte/svelte-wagmi-web3modal/src/components/ReadTokenSupply.svelte
<script lang="ts">
  import { readContract } from "@wagmi/core";
  import { useAsync } from "../composables/useAsync";
  import { daiContractConfig } from "../utils/contracts";
  import { onMount } from "svelte";

  const { state, execute: fetchTotalSupply } = useAsync(async () => {
    return await readContract({
      ...daiContractConfig,
      functionName: "totalSupply",
    });
  });
  $: ({ inProgress, error, result: supply } = $state);

  onMount(fetchTotalSupply);
</script>

<div>
  <div>
    Total Supply: {supply?.toString() ?? ""}
    <button on:click={fetchTotalSupply}
      >{inProgress ? "fetching..." : "refetch"}</button
    >
  </div>
  {#if error}
    <div>Error: {error?.message}</div>
  {/if}
</div>
