// templates/vue/nuxt3-wagmi/components/Balance.vue
<template>
  <div>
    <div>
      Connected wallet balance:
      {{ formattedBalance }}
      <button @click="getAccountBalance">refetch</button>
    </div>
    <div v-if="error">Error: {{ error?.message }}</div>
  </div>
</template>

<script lang="ts" setup>
import { ref, watch } from 'vue';
import { formatUnits } from 'viem';
import { getBalance } from '@wagmi/core';
import { useWagmi } from '../store/wagmi';
import { storeToRefs } from 'pinia';

const { account, wagmiConfig } = storeToRefs(useWagmi());
const balance = ref(null);
const error = ref(null);
const formattedBalance = ref('');

const getAccountBalance = async () => {
  if (!account.value) return;
  try {
    const balanceResult = await getBalance(wagmiConfig.value, { address: account.value.address });
    balance.value = balanceResult;
    formattedBalance.value = formatUnits(balanceResult.value, balanceResult.decimals);
  } catch (err) {
    error.value = err;
  }
};

watch(account, (newAccount) => {
  if (!newAccount.address) return;
  getAccountBalance();
}, { immediate: true });
</script>

// templates/svelte/vite-wagmi-web3modal/src/components/Balance.svelte
<script lang="ts">
  import { wagmiConfig, wagmiStore } from "../wagmi";
  import { getBalance } from "@wagmi/core";
  import { formatUnits } from "viem";
  import { writable, get } from "svelte/store";

  const formattedBalance = writable<string | null>(null);
  const error = writable<Error | null>(null);

  const getAccountBalance = async () => {
    const account = get(wagmiStore).account;
    if (account && account.address) {
      try {
        const result = await getBalance(wagmiConfig, { address: account.address });
        if (result) {
          formattedBalance.set(formatUnits(result.value, result.decimals));
        }
      } catch (err) {
        error.set(err as Error);
      }
    }
  };
  $: get(wagmiStore).account.address && getAccountBalance();
</script>

<div>
  <div>
    Connected wallet balance:
    {$formattedBalance ?? 'N/A'}
    <button on:click={getAccountBalance}>refetch</button>
  </div>
  {#if $error}
    <div>Error: {$error.message}</div>
  {/if}
</div>
