// templates/vue/nuxt3-wagmi-web3modal/components/BlockNumber.vue
<template>
  <div>
    {{ blockNumber?.toString() }}
  </div>
</template>

<script lang="ts" setup>
import { watchBlockNumber } from '@wagmi/core';
import { wagmiConfig } from '../store/wagmi.js';

const blockNumber = ref<bigint | null>(null);
watchBlockNumber(
  {
    ...wagmiConfig, 
    listen: true, 
  },
  {  
    onBlockNumber(block) {
     blockNumber.value = block;
  },
});
</script>

// templates/svelte/vite-wagmi-web3modal/src/components/BlockNumber.svelte
<script lang="ts">
  import { watchBlockNumber } from "@wagmi/core";
  import { wagmiConfig } from "../wagmi";
  import { onDestroy } from "svelte";

  let blockNumber: bigint | null = null;

  const unsubscribe = watchBlockNumber(
    {
      ...wagmiConfig,
      listen: true,
    },
    {
      onBlockNumber(block) {
        blockNumber = block;
      },
    }
  );

  onDestroy(() => {
    unsubscribe();
  });
</script>

<div>
  {#if blockNumber !== null}
    {blockNumber.toString()}
  {:else}
    Loading...
  {/if}
</div>
