// templates/vue/vite-wagmi-web3modal/src/components/ReadContracts.vue
<template>
  <div>
    <div>Data:</div>
    <div v-if="inProgress">loading...</div>
    <div v-if="results">
      <pre v-for="(item,index) in results" :key="index">{{ stringify(item) }}</pre>
    </div>
    <div v-if="error">Error: {{ error?.message }}</div>
  </div>
</template>

<script lang="ts" setup>
import { readContracts } from '@wagmi/core';

import { stringify } from '@/utils/formatters';
import { usdcContractConfig } from '@/utils/contracts';
import { useAsync } from '@/composables/useAsync';
import { account } from '@/wagmi';

const { result: results, execute: fetchContracts, inProgress, error} = useAsync(async () => {
  return await readContracts({
    contracts: [
      {
        ...usdcContractConfig,
        functionName: 'balanceOf',
        args: [account.value.address!],
      },
      {
        ...usdcContractConfig,
        functionName: 'name',
      },
      {
        ...usdcContractConfig,
        functionName: 'totalSupply',
      },
    ]
  })
});

fetchContracts();
</script>

// templates/svelte/vite-wagmi-web3modal/src/components/ReadContracts.svelte
<script lang="ts" setup>
  import { readContracts } from "@wagmi/core";
  import { wagmiStore } from "../wagmi";
  import { useAsync } from "../composables/useAsync";
  import { daiContractConfig } from "../utils/contracts";
  import { stringify } from "viem";
  import { onMount } from "svelte";

  $: ({ account } = $wagmiStore);

  const { state: asyncState, execute: fetchContracts } = useAsync(async () => {
    return await readContracts({
      contracts: [
        {
          ...daiContractConfig,
          functionName: "balanceOf",
          args: [account.address!],
        },
        {
          ...daiContractConfig,
          functionName: "name",
        },
        {
          ...daiContractConfig,
          functionName: "totalSupply",
        },
      ],
    });
  });

  $: ({ inProgress, error, result: results } = $asyncState);

  onMount(fetchContracts);
</script>

<div>
  <div>Data:</div>
  {#if inProgress}
    <div>loading...</div>
  {/if}

  {#if results}
    <div>
      {#each results as item (item)}
        <pre>{stringify(item)}</pre>
      {/each}
    </div>
  {/if}

  {#if error}
    <div>Error: {error?.message}</div>
  {/if}
</div>
