// templates/react/vite-ethers/src/components/BlockNumber.tsx
import { useState, useEffect } from 'react';
import { useEthereum } from './Context';

export function BlockNumber() {
  const { getProvider } = useEthereum();
  const [blockNumber, setBlockNumber] = useState<bigint | null>(null);

  useEffect(() => {
    const provider = getProvider();

    if (!provider) return;

    const onBlockHandler = (block: bigint) => {
      setBlockNumber(block);
    };

    provider.on("block", onBlockHandler);

    return () => {
      provider.off("block", onBlockHandler);
    };
  }, [getProvider]);

  return (
    <div>
      {blockNumber?.toString()}
    </div>
  );
}

// templates/vue/vite-wagmi-web3modal/src/components/BlockNumber.vue
<template>
  <div>
    {{ blockNumber?.toString() }}
  </div>
</template>

<script lang="ts" setup>
import { ref } from "vue"
import { watchBlockNumber } from '@wagmi/core';

const blockNumber = ref<bigint | null>(null);
watchBlockNumber({ listen: true }, (block) => {
  blockNumber.value = block;
});
</script>
