// templates/svelte/svelte-wagmi/src/components/WatchPendingTransactions.svelte
<script lang="ts">
  import { watchPendingTransactions, type Hash } from "@wagmi/core";

  let transactionHashes: Hash[] = [];

  watchPendingTransactions({}, (hashes) => {
    transactionHashes = [...transactionHashes, ...hashes];
  });
</script>

<div>
  <details>
    <summary>{transactionHashes.length} transaction hashes</summary>

    {transactionHashes.reverse().join("\n")}
  </details>
</div>

// templates/vue/vite-wagmi-web3modal/src/components/WatchPendingTransactions.vue
<template>
  <div>
    <details>
      <summary>{{ transactionHashes.length }} transaction hashes</summary>
      
      {{ transactionHashes.reverse().join('\n') }}
    </details>
  </div>
</template>

<script lang="ts" setup>
import { ref } from "vue"
import { watchPendingTransactions, type Hash } from '@wagmi/core';

const transactionHashes = ref<Hash[]>([]);

watchPendingTransactions({}, (hashes) => {
  transactionHashes.value.push(...hashes);
});
</script>
