// templates/vue/nuxt3-ethers5/components/WriteContractPrepared.vue
<template>
  <div>
    <form @submit.prevent="sendTransaction">
      <input v-model="amount" type="number" placeholder="allowance amount" />
      <button :disabled="prepareInProgress || !preparedTransaction" type="submit">Approve</button>
    </form>

    <div v-if="inProgress">Transaction pending...</div>
    <div v-else-if="transaction">
      <div>Transaction Hash: {{ transaction?.hash }}</div>
      <div>
        Transaction Receipt:
        <span v-if="receiptInProgress">pending...</span>
        <pre>{{ stringify(receipt, null, 2)}}</pre>
      </div>
    </div>

    <div v-if="prepareError">Preparing Transaction Error: {{ prepareError?.message }}</div>
    <div v-if="error">Error: {{ error?.message }}</div>
    <div v-if="receiptError">Receipt Error: {{ receiptError?.message }}</div>
  </div>
</template>

<script lang="ts" setup>
import { Contract } from 'zksync-ethers';

const { getSigner, getProvider } = useEthers()
const amount = ref<string | null>(null);

const getContractInstance = () => {
  return new Contract(daiContractConfig.address, daiContractConfig.abi, getSigner()!);
}

// Preparing the transaction
const { result: preparedTransaction, execute: prepareTransaction, inProgress: prepareInProgress, error: prepareError } = useAsync(async () => {
  const contract = getContractInstance();

  // random address for testing, replace with contract address that you want to allow to spend your tokens
  const spender = "0xa1cf087DB965Ab02Fb3CFaCe1f5c63935815f044"
  
  const gasPrice = await getProvider()!.getGasPrice();
  const gasLimit = await contract.estimateGas.approve(spender, amount.value);

  return {
    args: [spender, amount.value],
    overrides: {
      gasPrice,
      gasLimit
    }
  }
});

const { result: transaction, execute: sendTransaction, inProgress, error } = useAsync(async () => {
  const contract = getContractInstance();
  const transaction = preparedTransaction.value!;
  const result = await contract.approve(...transaction.args, transaction.overrides)
  waitForReceipt(result.hash);
  return result;
});

const { result: receipt, execute: waitForReceipt, inProgress: receiptInProgress, error: receiptError } = useAsync(async (transactionHash) => {
  return await getProvider()!.waitForTransaction(transactionHash);
});

watch(amount, () => {
  if (!amount.value) return;
  prepareTransaction();
}, { immediate: true });
</script>

// templates/react/vite-ethers5/src/components/WriteContractPrepared.tsx
import { useState, useEffect } from 'react';
import { Contract } from 'zksync-ethers';
import { useAsync } from '../hooks/useAsync';
import { daiContractConfig } from './contracts';
import { useEthereum } from './Context';

export function WriteContractPrepared() {
  const [amount, setAmount] = useState<string | null>(null);
  const { getSigner, getProvider } = useEthereum();

  const getContractInstance = () => {
    return new Contract(daiContractConfig.address, daiContractConfig.abi, getSigner()!);
  }

  const { result: preparedTransaction, execute: prepareTransaction, inProgress: prepareInProgress, error: prepareError } = useAsync(async () => {
    const contract = getContractInstance();
    
    // random address for testing, replace with contract address that you want to allow to spend your tokens
    const spender = "0xa1cf087DB965Ab02Fb3CFaCe1f5c63935815f044"

    const gasPrice = await getProvider()!.getGasPrice();
    const gasLimit = await contract.estimateGas.approve(spender, amount);

    return {
      args: [spender, amount],
      overrides: {
        gasPrice,
        gasLimit
      }
    };
  });

  const { result: transaction, execute: sendTransaction, inProgress, error } = useAsync(async () => {
    const contract = getContractInstance();
    const result = await contract.approve(...preparedTransaction!.args, preparedTransaction!.overrides);
    waitForReceipt(result.hash);
    return result;
  });

  const { result: receipt, execute: waitForReceipt, inProgress: receiptInProgress, error: receiptError } = useAsync(async (transactionHash) => {
    return await getProvider()!.waitForTransaction(transactionHash);
  });

  useEffect(() => {
    if (!amount) return;
    prepareTransaction();
  }, [amount]);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    sendTransaction();
  };

  return (
    <div>
      <form onSubmit={handleSubmit}>
        <input value={amount ?? ""} onChange={e => setAmount(e.target.value)} type="number" placeholder="allowance amount" />
        <button disabled={prepareInProgress || !preparedTransaction} type="submit">Approve</button>
      </form>

      {inProgress ? (
        <div>Transaction pending...</div>
      ) : (
        transaction && (
          <div>
            <div>Transaction Hash: {transaction?.hash}</div>
            <div>
              Transaction Receipt:
              {receiptInProgress ? (
                <span>pending...</span>
              ) : (
                <pre>{JSON.stringify(receipt, null, 2)}</pre>
              )}
            </div>
          </div>
        )
      )}

      {prepareError && <div>Preparing Transaction Error: {prepareError.message}</div>}
      {error && <div>Error: {error.message}</div>}
      {receiptError && <div>Receipt Error: {receiptError.message}</div>}
    </div>
  );
}
