// templates/react/vite-ethers5/src/components/Connect.tsx
import { useEthereum } from './Context';

export function Connect() {
  const { account, connect, disconnect } = useEthereum();

  return (
    <div>
      {account.isConnected ? (
        <button onClick={disconnect}>
          Disconnect wallet
        </button>
      ) : (
        <button onClick={connect}>
          Connect wallet
        </button>
      )}
    </div>
  )
}

// templates/vue/nuxt3-ethers/components/Connect.vue
<template>
  <div>
    <button v-if="account.isConnected" @click="disconnect">
      Disconnect wallet
    </button>

    <button v-else @click="connect()">
      Connect wallet
    </button>
  </div>
</template>

<script lang="ts" setup>
const { connect, disconnect } = useEthers()
const { account } = storeToRefs(useEthers())
</script>
