// templates/react/vite-ethers/src/components/Token.tsx
import { useState } from 'react';
import { Contract } from 'zksync-ethers';
import { useAsync } from '../hooks/useAsync';
import { erc20ABI, daiContractConfig } from './contracts'
import { useEthereum } from './Context';

export function Token() {
  const { getProvider } = useEthereum();
  const [tokenAddress, setTokenAddress] = useState<string>(daiContractConfig.address);

  const fetchTokenData = async (address: string) => {
    const contract = new Contract(address, erc20ABI, getProvider()!);
    const [symbol, name, decimals, supply] = await Promise.all([
      contract.symbol(),
      contract.name(),
      contract.decimals(),
      contract.totalSupply(),
    ]);
    return {
      symbol,
      name,
      decimals: decimals.toString(), 
      supply: supply.toString(),
    };
  };

  const { result: token, execute: fetchToken, inProgress, error } = useAsync(fetchTokenData);
  const fetchCurrentToken = () => fetchToken(tokenAddress);

  return (
    <div>
      <form onSubmit={(e) => { e.preventDefault(); fetchCurrentToken(); }}>
        <input
          value={tokenAddress}
          onChange={(e) => setTokenAddress(e.target.value)}
          placeholder="token address"
        />
        <button type="submit">fetch</button>
      </form>
      {inProgress ? (
        <div>Fetching token...</div>
      ) : token ? (
        <pre>{JSON.stringify(token, null, 4)}</pre>
      ) : error ? (
        <div>Error: {error.message}</div>
      ) : null}
    </div>
  );
}

// templates/vue/nuxt3-ethers/components/Token.vue
<template>
  <div>
    <form @submit.prevent="fetchCurrentToken">
      <input
        v-model="tokenAddress"
        placeholder="token address"
      />
      <button type="submit">fetch</button>
    </form>
    <div v-if="inProgress">Fetching token...</div>
    <div v-else-if="token">
      <pre>{{ stringify(token, null, 4) }}</pre>
    </div>
    <div v-else-if="error">Error: {{ error?.message }}</div>
  </div>
</template>

<script lang="ts" setup>
import { Contract } from 'zksync-ethers';

const { getProvider } = useEthers()

const tokenAddress = ref(daiContractConfig.address)

const { result: token, execute: fetchToken, inProgress, error} = useAsync(async (address: string) => {
  const contract = new Contract(address, erc20ABI, getProvider()!);
  const [symbol, name, decimals, supply] = await Promise.all([
    contract.symbol(),
    contract.name(),
    contract.decimals(),
    contract.totalSupply(),
  ]);
  return {
    symbol,
    name,
    decimals: decimals.toString(),
    supply: supply.toString(),
  }
})
const fetchCurrentToken = () => fetchToken(tokenAddress.value)
</script>
