// templates/vue/nuxt3-ethers/components/ReadTokenBalance.vue
<template>
  <div>
    <div>
      Token balance: {{ balance?.toString() }}
    </div>
    <div>
      <input v-model="address" type="text" placeholder="wallet address">
      <button @click="fetchBalance">{{ inProgress ? 'fetching...' : 'refetch' }}</button>
    </div>
    <div v-if="error">Error: {{ error?.message }}</div>
  </div>
</template>

<script lang="ts" setup>
import { Contract } from 'zksync-ethers';

const { getProvider } = useEthers()
const { account } = storeToRefs(useEthers());

const address = ref(account.value.address);

const { result: balance, execute: fetchBalance, inProgress, error} = useAsync(async () => {
  const contract = new Contract(daiContractConfig.address, daiContractConfig.abi, getProvider()!);
  return contract.balanceOf(address.value!);
});

fetchBalance();
</script>

// templates/svelte/vite-ethers5/src/components/ReadTokenBalance.svelte
<script lang="ts">
  import { Contract } from "zksync-ethers";
  import { useAsync } from "../composables/useAsync";
  import { etherStore } from "../ethers";
  import { daiContractConfig } from "../utils/contracts";
  import { onMount } from "svelte";

  const { getProvider } = etherStore;
  $: ({ account } = $etherStore);

  let { execute: fetchBalance, state } = useAsync(async () => {
    const contract = new Contract(
      daiContractConfig.address,
      daiContractConfig.abi,
      getProvider()!,
    );

    return contract.balanceOf(account.address!);
  });
  $: ({ inProgress, error, result: balance } = $state);

  onMount(fetchBalance);
</script>

<div>
  <div>
    Token balance: {balance?.toString() ?? ""}
  </div>
  <div>
    <input
      bind:value={account.address}
      type="text"
      placeholder="wallet address"
    />
    <button on:click={fetchBalance}
      >{inProgress ? "fetching..." : "refetch"}</button
    >
  </div>
  {#if error}
    <div>Error: {error?.message}</div>
  {/if}
</div>
