// templates/vue/nuxt3-ethers5/components/SendTransaction.vue
<template>
  <div>
    <form @submit.prevent="sendTransaction">
      <input v-model="address" placeholder="address" />
      <input v-model="value" placeholder="value (ether)" />
      <button type="submit">Send</button>
    </form>

    <div v-if="inProgress">Transaction pending...</div>
    <div v-else-if="transaction">
      <div>Transaction Hash: {{ transaction?.hash }}</div>
      <div>
        Transaction Receipt:
        <span v-if="receiptInProgress">pending...</span>
        <pre>{{ stringify(receipt, null, 2)}}</pre>
      </div>
    </div>

    <div v-if="error">Error: {{ error?.message }}</div>
    <div v-if="receiptError">Receipt Error: {{ receiptError?.message }}</div>
  </div>
</template>

<script lang="ts" setup>
import { parseEther } from 'ethers/lib/utils';

const { getSigner, getProvider } = useEthers()

const address = ref<string | null>(null);
const value = ref<string | null>(null);

const { result: transaction, execute: sendTransaction, inProgress, error} = useAsync(async () => {
  const result = await getSigner()!.sendTransaction({
    to: address.value!,
    value: parseEther(value.value!),
  })
  waitForReceipt(result.hash);
  return result;
});
const { result: receipt, execute: waitForReceipt, inProgress: receiptInProgress, error: receiptError} = useAsync(async (transactionHash) => {
  return await getProvider()!.waitForTransaction(transactionHash);
});
</script>

// templates/svelte/vite-ethers5/src/components/SendTransaction.svelte
<script lang="ts">
  import { etherStore } from "../ethers";
  import { useAsync } from "../composables/useAsync";
  import { stringify } from "../utils/formatters";
  import { parseEther } from "ethers/lib/utils";

  const { getSigner, getProvider } = etherStore;

  let address: string | null = "";
  let value: string | null = "";

  const { state: transactionState, execute: sendTransaction } = useAsync(
    async () => {
      const result = await (await getSigner())!.sendTransaction({
        to: address!,
        value: parseEther(value!),
      });
      waitForReceipt(result.hash);
      return result;
    }
  );
  $: ({ result: transaction, inProgress, error } = $transactionState);

  const { state: receiptState, execute: waitForReceipt } = useAsync(
    async (transactionHash) => {
      return await getProvider()!.waitForTransaction(transactionHash);
    }
  );
  $: ({
    result: receipt,
    inProgress: receiptInProgress,
    error: receiptError,
  } = $receiptState);
</script>

<div>
  <form on:submit|preventDefault={sendTransaction}>
    <input bind:value={address} placeholder="address" />
    <input bind:value placeholder="value (ether)" />
    <button type="submit">Send</button>
  </form>

  {#if inProgress}
    <div>Transaction pending...</div>
  {:else if transaction}
    <div>
      <div>Transaction Hash: {transaction?.hash}</div>
      <div>
        Transaction Receipt:
        {#if receiptInProgress}
          <span>pending...</span>
        {/if}
        <pre>{stringify(receipt, null, 2)}</pre>
      </div>
    </div>
  {/if}

  {#if error}
    <div>Error: {error?.message}</div>
  {/if}
  {#if receiptError}
    <div>Receipt Error: {receiptError?.message}</div>
  {/if}
</div>
