// templates/react/vite-ethers5/src/components/WatchPendingTransactions.tsx
import { useEffect, useState } from 'react';
import { useEthereum } from './Context';

export function WatchPendingTransactions() {
  const { getProvider } = useEthereum();
  const [transactionHashes, setTransactionHashes] = useState<string[]>([]);

  useEffect(() => {
    const provider = getProvider();

    const onBlock = async (blockNumber: number) => {
      const block = await provider?.getBlock(blockNumber);
      if (block && block.transactions) {
        setTransactionHashes(prevHashes => [...prevHashes, ...block.transactions]);
      }
    };

    if (provider) {
      provider.on("block", onBlock);
    }

    return () => {
      if (provider) {
        provider.off("block", onBlock);
      }
    };
  }, []);

  return (
    <div>
      <details>
        <summary>{transactionHashes.length} transaction hashes</summary>
        
        <pre>{[...transactionHashes].reverse().join('\n')}</pre>
      </details>
    </div>
  );
}

// templates/svelte/vite-ethers5/src/components/WatchPendingTransactions.svelte
<script lang="ts">
  import { etherStore } from "../ethers";

  const { getProvider } = etherStore;

  let transactionHashes: string[] = [];

  let provider = getProvider()!;

  provider.on("block", async (blockNumber: number) => {
    const block = await provider.getBlock(blockNumber);
    transactionHashes = [...transactionHashes, ...block.transactions];
  });
</script>

<div>
  <details>
    <summary>{transactionHashes.length} transaction hashes</summary>

    {transactionHashes.reverse().join("\n")}
  </details>
</div>
