// templates/vue/vite-ethers/src/components/ReadTokenSupply.vue
<template>
  <div>
    <div>
      Total Supply: {{ supply?.toString() }}
      <button @click="fetchTotalSupply">{{ inProgress ? 'fetching...' : 'refetch' }}</button>
    </div>
    <div v-if="error">Error: {{ error?.message }}</div>
  </div>
</template>

<script lang="ts" setup>
import { Contract } from 'zksync-ethers';

import { daiContractConfig } from '@/utils/contracts';
import { useAsync } from '@/composables/useAsync';
import { getProvider } from "@/ethers"

const { result: supply, execute: fetchTotalSupply, inProgress, error} = useAsync(async () => {
  const contract = new Contract(daiContractConfig.address, daiContractConfig.abi, getProvider()!);
  return await contract.totalSupply();
});

fetchTotalSupply();
</script>

// templates/svelte/sveltekit-ethers/src/components/ReadTokenSupply.svelte
<script lang="ts">
  import { Contract } from "zksync-ethers";
  import { etherStore } from "../stores/ethers";
  import { useAsync } from "../composables/useAsync";
  import { daiContractConfig } from "../utils/contracts";
  import { onMount } from "svelte";

  const { getProvider } = etherStore;

  const { state, execute: fetchTotalSupply } = useAsync(async () => {
    const contract = new Contract(
      daiContractConfig.address,
      daiContractConfig.abi,
      getProvider()!,
    );
    return await contract.totalSupply();
  });
  $: ({ inProgress, error, result: supply } = $state);

  onMount(fetchTotalSupply);
</script>

<div>
  <div>
    Total Supply: {supply?.toString() ?? ""}
    <button on:click={fetchTotalSupply}
      >{inProgress ? "fetching..." : "refetch"}</button
    >
  </div>
  {#if error}
    <div>Error: {error?.message}</div>
  {/if}
</div>
