// templates/vue/nuxt3-wagmi/pages/index.vue
<template>
  <div>
    <h1>zkSync + wagmi + Nuxt 3</h1>

    <Connect />

    <Connected>
      <hr />
      <h2>Network</h2>
      <p>
        <strong>Make sure to connect your wallet to zkSync Testnet for full functionality</strong>
        <br />
        or update to a different contract address
      </p>
      <NetworkSwitcher />
      <br />
      <hr />
      <h2>Account</h2>
      <Account />
      <br />
      <hr />
      <h2>Balance</h2>
      <Balance />
      <br />
      <FindBalance />
      <br />
      <hr />
      <h2>Block Number</h2>
      <BlockNumber />
      <br />
      <hr />
      <h2>Read Contract</h2>
      <ReadTokenBalance />
      <br />
      <ReadTokenSupply />
      <br />
      <hr />
      <h2>Read Contracts</h2>
      <ReadContracts />
      <br />
      <hr />
      <h2>Send Transaction</h2>
      <SendTransaction />
      <br />
      <hr />
      <h2>Send Transaction (Prepared)</h2>
      <SendTransactionPrepared />
      <br />
      <hr />
      <h2>Sign Message</h2>
      <SignMessage />
      <br />
      <hr />
      <h2>Sign Typed Data</h2>
      <SignTypedData />
      <br />
      <hr />
      <h2>Token</h2>
      <Token />
      <br />
      <hr />
      <h2>Watch Contract Events</h2>
      <WatchContractEvents />
      <br />
      <hr />
      <h2>Watch Pending Transactions</h2>
      <WatchPendingTransactions />
      <br />
      <hr />
      <h2>Write Contract</h2>
      <WriteContract />
      <br />
      <hr />
      <h2>Write Contract (Prepared)</h2>
      <WriteContractPrepared />
    </Connected>
  </div>
</template>

<script lang="ts" setup>
useWagmi();
</script>

// templates/react/next-web3js/src/pages/index.tsx
'use client';

import { useEthereum } from '../components/Context'
import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { BlockNumber } from '../components/BlockNumber';
import { NetworkSwitcher } from '../components/NetworkSwitcher';
import { Account } from '../components/Account';
import { Connect } from "../components/Connect";
import { Balance } from '../components/Balance';
import { ReadContract } from '../components/ReadContract'
import { SendTransaction } from '../components/SendTransaction';
import { SignMessage } from '../components/SignMessage';
import { SignTypedData } from '../components/SignTypedData';
import { WatchContractEvents } from '../components/WatchContractEvents';
import { Token } from '../components/Token';
import { WatchPendingTransactions } from '../components/WatchPendingTransactions'
import { SendTransactionPrepared } from '../components/SendTransactionPrepared';
import { WriteContract } from '../components/WriteContract';
import { WriteContractPrepared } from '../components/WriteContractPrepared';
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { account } = useEthereum();
  return (
    <>
      <Head>
        <title>Web3.js + ZKsync + Next.js </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div>
          <Connect />
          {account.isConnected &&
            <>
              <hr />
              <h2>Network</h2>
              <p>
                <strong>Make sure to connect your wallet to ZKsync Testnet for full functionality</strong>
                <br />
                or update to a different contract address
              </p>
              <NetworkSwitcher />
              <br />
              <hr />
              <h2>Account</h2>
              <Account />
              <br />
              <hr />
              <h2>Balance</h2>
              <Balance />
              <br />
              <hr />
              <h2>Block Number</h2>
              <BlockNumber />
              <br />
              <hr />
              <h2>Read Contract</h2>
              <ReadContract />
              <br />
              <hr />
              <h2>Send Transaction</h2>
              <SendTransaction />
              <br />
              <hr />
              <h2>Send Transaction (Prepared)</h2>
              <SendTransactionPrepared />
              <h2>Sign Message</h2>
              <SignMessage />
              <br />
              <hr />
              <h2>Sign Typed Data</h2>
              <SignTypedData />
              <br />
              <hr />
              <h2>Token</h2>
              <Token />
              <br />
              <hr />
              <h2>Watch Contract Events</h2>
              <WatchContractEvents />
              <br />
              <hr />
              <WatchPendingTransactions />
              <br />
              <hr />
              <h2>Write Contract</h2>
              <WriteContract />
              <br />
              <hr />
              <h2>Write Contract (Prepared)</h2>
              <WriteContractPrepared />
            </>
          }
        </div>
      </main>
    </>
  );
}
