// templates/svelte/sveltekit-ethers5/src/components/FindBalance.svelte
<script lang="ts" setup>
  import { useAsync } from "../composables/useAsync";
  import { etherStore } from "../stores/ethers";
  import { formatEther } from "ethers/lib/utils";

  const { state: asyncState, execute: fetchBalance } = useAsync((address) =>
    etherStore.getProvider()!.getBalance(address)
  );
  $: ({ result: balance, error, inProgress } = $asyncState);

  let address = "";
</script>

<div>
  <div>
    Find balance:
    <input bind:value={address} type="text" placeholder="wallet address" />
    <button on:click={() => fetchBalance(address)}
      >{inProgress ? "fetching..." : "fetch"}</button
    >
  </div>
  <div>{balance ? formatEther(balance) : ""}</div>
  {#if error}
    <div>Error: {error?.message}</div>
  {/if}
</div>

// templates/vue/vite-ethers5/src/components/FindBalance.vue
<template>
  <div>
    <div>
      Find balance:
      <input v-model="address" type="text" placeholder="wallet address">
      <button @click="() => fetchBalance(address)">{{ inProgress ? 'fetching...' : 'fetch' }}</button>
    </div>
    <div>{{ balance ? formatEther(balance): "" }}</div>
    <div v-if="error">Error: {{ error?.message }}</div>
  </div>
</template>

<script lang="ts" setup>
import { ref } from "vue";
import { formatEther } from 'ethers/lib/utils';

import { useAsync } from '@/composables/useAsync';
import { getProvider } from "@/ethers"

const address = ref("");

const { result: balance, execute: fetchBalance, inProgress, error} = useAsync((address) => getProvider()!.getBalance(address));
</script>
