// templates/svelte/sveltekit-ethers5/src/components/NetworkSwitcher.svelte
<script lang="ts" setup>
  import { etherStore, chains } from "../stores/ethers";
  import { useAsync } from "../composables/useAsync";

  const { switchNetwork: switchToChainByID } = etherStore;
  $: ({ network } = $etherStore);

  const { execute: switchNetwork, state: asyncState } =
    useAsync(switchToChainByID);
  $: ({ inProgress, error } = $asyncState);
</script>

<div>
  <div>
    Connected to {network?.name ?? network?.id}
    {#if network?.unsupported}
      <span>(unsupported)</span>
    {/if}
  </div>
  <br />
  <div>
    Switch to:
    {#each chains as item (item.id)}
      <button on:click={() => switchNetwork(item.id)}>
        {item.name}
      </button>
    {/each}
  </div>
  {#if error}
    <div>Error: {error?.message}</div>
  {/if}
</div>

// templates/vue/vite-ethers5/src/components/NetworkSwitcher.vue
<template>
  <div>
    <div>
      Connected to {{ network?.name ?? network?.id }}
      <span v-if="network?.unsupported">(unsupported)</span>
    </div>
    <br />
    <div>
      Switch to:
      <button v-for="(item, index) in chains" :key="index" @click="switchNetwork(item.id)">
        {{ item.name }}
      </button>
    </div>

    <div v-if="error">Error: {{ error?.message }}</div>
  </div>
</template>

<script lang="ts" setup>
import { useAsync } from '@/composables/useAsync';
import { chains, network, switchNetwork as switchToChainByID } from "@/ethers";

const { execute: switchNetwork, inProgress, error} = useAsync(switchToChainByID);
</script>
