// templates/svelte/sveltekit-ethers5/src/components/SendTransactionPrepared.svelte
<script lang="ts">
  import { parseEther } from "ethers/lib/utils";
  import { stringify } from "../utils/formatters";
  import { etherStore } from "../stores/ethers";
  import { useAsync } from "../composables/useAsync";

  const { getSigner, getProvider } = etherStore;

  let address: string | null = "";
  let value: string | null = "";

  const { state: preparedTransactionState, execute: prepareTransaction } =
    useAsync(async () => {
      const transaction = {
        to: address!,
        value: parseEther(value!),
      };
      const gasPrice = await getProvider()!.getGasPrice();
      const gasLimit = await (await getSigner())!.estimateGas({
        to: address!,
        value: parseEther(value!),
        gasPrice,
      });

      return {
        ...transaction,
        gasPrice,
        gasLimit,
      };
    });
  $: ({
    result: preparedTransaction,
    inProgress: prepareInProgress,
    error: prepareError,
  } = $preparedTransactionState);

  const { state: transactionState, execute: sendTransaction } = useAsync(
    async () => {
      const result = await (await getSigner())!.sendTransaction(
        preparedTransaction!
      );
      waitForReceipt(result.hash);
      return result;
    }
  );
  $: ({ result: transaction, inProgress, error } = $transactionState);

  const { state: receiptState, execute: waitForReceipt } = useAsync(
    async (transactionHash) => {
      return await getProvider()!.waitForTransaction(transactionHash);
    }
  );
  $: ({
    result: receipt,
    inProgress: receiptInProgress,
    error: receiptError,
  } = $receiptState);

  $: address && value && prepareTransaction();
</script>

<div>
  <form on:submit|preventDefault={sendTransaction}>
    <input bind:value={address} placeholder="address" />
    <input bind:value placeholder="value (ether)" />
    <button disabled={prepareInProgress || !preparedTransaction} type="submit"
      >Send</button
    >
  </form>

  {#if inProgress}
    <div>Transaction pending...</div>
  {:else if transaction}
    <div>
      <div>Transaction Hash: {transaction?.hash}</div>
      <div>
        Transaction Receipt:
        {#if receiptInProgress}
          <span>pending...</span>
        {/if}
        <pre>{stringify(receipt, null, 2)}</pre>
      </div>
    </div>
  {/if}

  {#if prepareError}
    <div>Preparing Transaction Error: {prepareError?.message}</div>
  {/if}
  {#if error}
    <div>Error: {error?.message}</div>
  {/if}
  {#if receiptError}
    <div>Receipt Error: {receiptError?.message}</div>
  {/if}
</div>

// templates/vue/vite-ethers5/src/components/SendTransactionPrepared.vue
<template>
  <div>
    <form @submit.prevent="sendTransaction">
      <input v-model="address" placeholder="address" />
      <input v-model="value" placeholder="value (ether)" />
      <button :disabled="prepareInProgress || !preparedTransaction" type="submit">Send</button>
    </form>

    <div v-if="inProgress">Transaction pending...</div>
    <div v-else-if="transaction">
      <div>Transaction Hash: {{ transaction?.hash }}</div>
      <div>
        Transaction Receipt:
        <span v-if="receiptInProgress">pending...</span>
        <pre>{{ stringify(receipt, null, 2)}}</pre>
      </div>
    </div>

    <div v-if="prepareError">Preparing Transaction Error: {{ prepareError?.message }}</div>
    <div v-if="error">Error: {{ error?.message }}</div>
    <div v-if="receiptError">Receipt Error: {{ receiptError?.message }}</div>
  </div>
</template>

<script lang="ts" setup>
import { ref, watch } from 'vue';
import { parseEther } from 'ethers/lib/utils';

import { stringify } from '@/utils/formatters';
import { useAsync } from '@/composables/useAsync';
import { getSigner, getProvider } from "@/ethers"

const address = ref<string | null>(null);
const value = ref<string | null>(null);

const { result: preparedTransaction, execute: prepareTransaction, inProgress: prepareInProgress, error: prepareError} = useAsync(async () => {
  const transaction = {
    to: address.value!,
    value: parseEther(value.value!),
  }
  const gasPrice = await getProvider()!.getGasPrice();
  const gasLimit = await getSigner()!.estimateGas({
    to: address.value!,
    value: parseEther(value.value!),
    gasPrice,
  });

  return {
    ...transaction,
    gasPrice,
    gasLimit,
  }
});
const { result: transaction, execute: sendTransaction, inProgress, error} = useAsync(async () => {
  const result = await getSigner()!.sendTransaction(preparedTransaction.value!)
  waitForReceipt(result.hash);
  return result;
});
const { result: receipt, execute: waitForReceipt, inProgress: receiptInProgress, error: receiptError} = useAsync(async (transactionHash) => {
  return await getProvider()!.waitForTransaction(transactionHash);
});

watch([address, value], () => {
  if (!address.value || !value.value) return;
  prepareTransaction();
}, { immediate: true });
</script>
