// templates/svelte/vite-ethers5/src/components/WatchPendingTransactions.svelte
<script lang="ts">
  import { etherStore } from "../ethers";

  const { getProvider } = etherStore;

  let transactionHashes: string[] = [];

  let provider = getProvider()!;

  provider.on("block", async (blockNumber: number) => {
    const block = await provider.getBlock(blockNumber);
    transactionHashes = [...transactionHashes, ...block.transactions];
  });
</script>

<div>
  <details>
    <summary>{transactionHashes.length} transaction hashes</summary>

    {transactionHashes.reverse().join("\n")}
  </details>
</div>

// templates/vue/vite-ethers5/src/components/WatchPendingTransactions.vue
<template>
  <div>
    <details>
      <summary>{{ transactionHashes.length }} transaction hashes</summary>
      
      {{ transactionHashes.reverse().join('\n') }}
    </details>
  </div>
</template>

<script lang="ts" setup>
import { ref } from 'vue';

import { getProvider } from "@/ethers"

const transactionHashes = ref<string[]>([]);

const provider = getProvider()!;

provider.on("block", async (blockNumber) => {
  const block = await provider.getBlock(blockNumber);
  transactionHashes.value.push(...block.transactions);
});
</script>
