// templates/svelte/vite-ethers5/src/components/SignMessage.svelte
<script lang="ts">
  import { verifyMessage } from "ethers/lib/utils";
  import { etherStore } from "../ethers";
  import { useAsync } from "../composables/useAsync";

  const { getSigner } = etherStore;

  let message: string | null = null;

  const { state, execute: signMessage } = useAsync(async () => {
    const signature = await (await getSigner())!.signMessage(message!);
    const recoveredAddress = verifyMessage(message!, signature);

    return {
      signature,
      recoveredAddress,
    };
  });
  $: ({ result, inProgress, error } = $state);
</script>

<div>
  <form on:submit|preventDefault={signMessage}>
    <input bind:value={message} placeholder="message" required />
    <button type="submit">Sign Message</button>
  </form>

  {#if result && !inProgress}
    <div>
      <div>Signature: {result.signature}</div>
      <div>Recovered address: {result.recoveredAddress}</div>
    </div>
  {/if}

  {#if error}
    <div>Error: {error?.message}</div>
  {/if}
</div>

// templates/vue/nuxt3-ethers5/components/SignMessage.vue
<template>
  <div>
    <form @submit.prevent="signMessage">
      <input v-model="message" placeholder="message" required />
      <button type="submit">Sign Message</button>
    </form>

    <div v-if="result && !inProgress">
      <div>
        <div>Signature: {{ result.signature }}</div>
        <div>Recovered address: {{ result.recoveredAddress }}</div>
      </div>
    </div>

    <div v-if="error">Error: {{ error?.message }}</div>
  </div>
</template>

<script lang="ts" setup>
import { verifyMessage } from 'ethers/lib/utils';

const { getSigner } = useEthers()

const message = ref<string | null>(null);

const { result, execute: signMessage, inProgress, error} = useAsync(async () => {
  const signature =  await getSigner()!.signMessage(message.value!);
  const recoveredAddress = verifyMessage(message.value!, signature)

  return {
    signature,
    recoveredAddress
  }
});
</script>
