// templates/vue/nuxt3-wagmi-web3modal/components/Token.vue
<template>
  <div>
    <form @submit.prevent="fetchCurrentToken">
      <input
        v-model="tokenAddress"
        placeholder="token address"
      />
      <button type="submit">fetch</button>
    </form>
    <div v-if="inProgress">Fetching token...</div>
    <div v-else-if="token">
      <pre>{{ stringify(token, null, 4) }}</pre>
    </div>
    <div v-else-if="error">Error: {{ error?.message }}</div>
  </div>
</template>

<script lang="ts" setup>
import { fetchToken as wagmiFetchToken } from '@wagmi/core';

const tokenAddress = ref(daiContractConfig.address)

const { result: token, execute: fetchToken, inProgress, error} = useAsync(wagmiFetchToken)
const fetchCurrentToken = () => fetchToken({ address: tokenAddress.value })
</script>

// templates/svelte/sveltekit-wagmi-web3modal/src/components/Token.svelte
<script lang="ts">
  import { fetchToken as wagmiFetchToken } from "@wagmi/core";
  import { daiContractConfig } from "../utils/contracts";
  import { useAsync } from "../composables/useAsync";
  import { stringify } from "../utils/formatters";

  let tokenAddress = daiContractConfig.address;

  const { state, execute: fetchToken } = useAsync(wagmiFetchToken);
  $: ({ result: token, inProgress, error } = $state);
  const fetchCurrentToken = () => fetchToken({ address: tokenAddress });
</script>

<div>
  <form on:submit|preventDefault={fetchCurrentToken}>
    <input bind:value={tokenAddress} placeholder="token address" />
    <button type="submit">fetch</button>
  </form>
  {#if inProgress}
    <div>Fetching token...</div>
  {:else if token}
    <pre>{stringify(token, null, 4)}</pre>
  {:else if error}
    <div>Error: {error?.message}</div>
  {/if}
</div>
