// templates/vue/nuxt3-wagmi-web3modal/components/Balance.vue
<template>
  <div>
    <div>
      Connected wallet balance:
      {{ balance?.formatted }}
      <button @click="getAccountBalance">refetch</button>
    </div>
    <div v-if="error">Error: {{ error?.message }}</div>
  </div>
</template>

<script lang="ts" setup>
import { fetchBalance as wagmiFetchBalance } from '@wagmi/core';

const { account } = storeToRefs(useWagmi());

const { result: balance, execute: fetchBalance, inProgress, error} = useAsync(wagmiFetchBalance);
const getAccountBalance = () => fetchBalance({ address: account.value.address! });

watch(account, ({ address }) => {
  if (!address) return;
  getAccountBalance();
}, { immediate: true });
</script>

// templates/svelte/vite-wagmi/src/components/Balance.svelte
<script lang="ts">
  import { wagmiStore } from "../wagmi";
  import { useAsync } from "../composables/useAsync";
  import { fetchBalance as wagmiFetchBalance } from "@wagmi/core";

  const { state: asyncState, execute: fetchBalance } =
    useAsync(wagmiFetchBalance);
  $: ({ result: balance, error, inProgress } = $asyncState);

  const getAccountBalance = () =>
    fetchBalance({ address: $wagmiStore.account.address! });
  $: $wagmiStore.account.address && getAccountBalance();
</script>

<div>
  <div>
    Connected wallet balance:
    {balance?.formatted}
    <button on:click={getAccountBalance}>refetch</button>
  </div>
  {#if error}
    Error: {error?.message}
  {/if}
</div>
