// templates/vue/vite-wagmi/src/components/Connect.vue
<template>
  <div>
    <button v-if="account.isConnected" @click="disconnect">
      Disconnect from {{ account.connector?.name }}
    </button>

    <template v-else>
      <button v-for="item in config.connectors" :key="item.id" @click="connect({ connector: item })">
        {{ item.name }}
      </button>
    </template>
  </div>
</template>

<script lang="ts" setup>
import { connect, disconnect, getConfig } from '@wagmi/core';
import { account } from "@/wagmi"

const config = getConfig();
</script>

// templates/svelte/vite-wagmi/src/components/Connect.svelte
<script lang="ts">
  import { wagmiStore } from "../wagmi";
  import { connect, disconnect, getConfig } from "@wagmi/core";

  const config = getConfig();
  $: ({ account } = $wagmiStore);
</script>

<div>
  {#if account.isConnected}
    <button on:click={disconnect}>
      Disconnect from {account.connector?.name}
    </button>
  {:else}
    {#each config.connectors as item (item.id)}
      <button on:click={() => connect({ connector: item })}>
        {item.name}
      </button>
    {/each}
  {/if}
</div>
