// templates/vue/nuxt3-wagmi/components/Connect.vue
<template>
  <div>
    <button v-if="account.isConnected" @click="handleDisconnect">
      Disconnect from {{ account.connector?.name }}
    </button>

    <template v-else>
      <button
        v-for="item in connectors"
        :key="item.id"
        @click="() => handleConnect(item)"
      >
        Connect with {{ item.name }}
      </button>
    </template>
  </div>
</template>

<script lang="ts" setup>
import { ref } from 'vue';
import { connect, disconnect, type Connector } from '@wagmi/core';

const connectors = ref(wagmiConfig.connectors);
const { account } = storeToRefs(useWagmi());

const handleConnect = async (connector: Connector) => {
  try {
    await connect(wagmiConfig,{ connector }); 
  } catch (error) {
    console.error("Error connecting:", error);
  }
};

const handleDisconnect = async () => {
  try {
    await disconnect(wagmiConfig); 
    account.value.isConnected = false; 
  } catch (error) {
    console.error("Error disconnecting:", error);
  }
};
</script>

// templates/svelte/vite-wagmi/src/components/Connect.svelte
<script lang="ts">
  import { wagmiConfig, wagmiStore } from "../wagmi";
  import { connect, disconnect, type Connector } from "@wagmi/core";
  import { get } from "svelte/store";

  $: ({ account } = get(wagmiStore));

  const handleConnect = async (connector: Connector) => {
    try {
      await connect(wagmiConfig, { connector });
    } catch (error) {
      console.error("Error connecting:", error);
    }
  };

  const handleDisconnect = async () => {
    try {
      await disconnect(wagmiConfig);
      account.isConnected = false;
    } catch (error) {
      console.error("Error disconnecting:", error);
    }
  };
</script>

<div>
  {#if account.isConnected}
    <button on:click={handleDisconnect}>
      Disconnect from {account.connector?.name}
    </button>
  {:else}
    {#each wagmiConfig.connectors as item (item.id)}
      <button on:click={() => handleConnect(item)}>
        Connect with {item.name}
      </button>
    {/each}
  {/if}
</div>
